// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsqvfuwqncmjwcnxvumk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzcXZmdXdxbmNtandjbnh2dW1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTEzMjcsImV4cCI6MjA2MzkyNzMyN30.oUh9Hc1syWYqlsF3Uo-6unXPN6iIlFCyipCdpFsSMnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);